"""creating a relationship between Jurisdictions and Officials

Revision ID: 4eca0cdb8aba
Revises: dcf1b5daea46
Create Date: 2026-02-25 15:53:29.218850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eca0cdb8aba'
down_revision: Union[str, Sequence[str], None] = 'dcf1b5daea46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('officials', sa.Column('jurisdiction_id', sa.Integer(), nullable=False))
    op.add_column('officials', sa.Column('name_suffix', sa.String(), nullable=False))
    op.add_column('officials', sa.Column('cleaned_name', sa.String(), nullable=False))
    op.create_foreign_key(None, 'officials', 'jurisdictions', ['jurisdiction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'officials', type_='foreignkey')
    op.drop_column('officials', 'cleaned_name')
    op.drop_column('officials', 'name_suffix')
    op.drop_column('officials', 'jurisdiction_id')
    # ### end Alembic commands ###
