"""progress on database constructing

Revision ID: 5636283c10f5
Revises: 4eca0cdb8aba
Create Date: 2026-02-25 17:40:51.191963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5636283c10f5'
down_revision: Union[str, Sequence[str], None] = '4eca0cdb8aba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_raw', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participant_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jurisdiction_id', sa.Integer(), nullable=False),
    sa.Column('decision_date', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('decision_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conflict_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('officials_id', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['officials_id'], ['officials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conflict_flags')
    op.drop_table('decisions')
    op.drop_table('participant_matches')
    op.drop_table('decision_participants')
    # ### end Alembic commands ###
