"""insert message

Revision ID: dcf1b5daea46
Revises: a485939687eb
Create Date: 2026-02-25 14:33:27.844885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcf1b5daea46'
down_revision: Union[str, Sequence[str], None] = 'a485939687eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jurisdictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jurisdiction_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('officials', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('officials', sa.Column('last_name', sa.String(), nullable=False))
    op.add_column('officials', sa.Column('middle_name', sa.String(), nullable=False))
    op.drop_index(op.f('ix_officials_id'), table_name='officials')
    op.drop_column('officials', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('officials', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_officials_id'), 'officials', ['id'], unique=False)
    op.drop_column('officials', 'middle_name')
    op.drop_column('officials', 'last_name')
    op.drop_column('officials', 'first_name')
    op.drop_table('jurisdictions')
    # ### end Alembic commands ###
